#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


echo '🏗️👷 Styling, testing and building your project before committing'


yarn build ||
(
    echo '❌👷🔨❌ Your Next.js build failed ❌👷🔨❌
            Next.js build failed: View the errors above to see why.
    '
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
